In [1]:
import dataset_utils
import numpy as np 

from ucimlrepo import fetch_ucirepo 
from keras.datasets import mnist
import pandas as pd


# Iris Dataset

In [2]:
iris = fetch_ucirepo(id=53) 


# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
X = X.to_numpy()
dataset_utils.fvecs_write("fvec_datasets/iris.fvec", X)

# Seeds

In [12]:
data_seeds = pd.read_csv('data/UCI/seeds/seeds_dataset.txt', sep='\t',
                         header=None,
                         names=['x1','x2','x3','x4','x5','x6','x7','class'])

X = data_seeds.copy().drop(['class'], axis=1)
X = X.to_numpy()
y = data_seeds[['class']]

In [14]:
dataset_utils.fvecs_write("fvec_datasets/seeds.fvec", X)

# Cancer

In [20]:
# fetch dataset 
breast_cancer_wisconsin_original = fetch_ucirepo(id=15) 

# data (as pandas dataframes) 
X = breast_cancer_wisconsin_original.data.features 
y = breast_cancer_wisconsin_original.data.targets 
y_column = 'Class'
X.fillna(method = 'ffill',inplace=True)
X = X.to_numpy()
dataset_utils.fvecs_write("fvec_datasets/Cancer.fvec", X)

C:\Users\felip\AppData\Local\Temp\ipykernel_23164\366605026.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X.fillna(method = 'ffill',inplace=True)
C:\Users\felip\AppData\Local\Temp\ipykernel_23164\366605026.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna(method = 'ffill',inplace=True)


In [6]:
# fetch dataset 
import dataset_utils
from dataset_utils import fvecs_read
breast_cancer_wisconsin_original = fetch_ucirepo(id=15) 

# data (as pandas dataframes) 
X = breast_cancer_wisconsin_original.data.features 
y = breast_cancer_wisconsin_original.data.targets 
y_column = 'Class'
X.fillna(method = 'ffill',inplace=True)
X = X.to_numpy()

Cancer_fvec = dataset_utils.fvecs_read("./fvec_datasets/Cancer.fvec")


[[ 5.  1.  1. ...  3.  1.  1.]
 [ 5.  4.  4. ...  3.  2.  1.]
 [ 3.  1.  1. ...  3.  1.  1.]
 ...
 [ 5. 10. 10. ...  8. 10.  2.]
 [ 4.  8.  6. ... 10.  6.  1.]
 [ 4.  8.  8. ... 10.  4.  1.]]
[[ 5.  1.  1. ...  3.  1.  1.]
 [ 5.  4.  4. ...  3.  2.  1.]
 [ 3.  1.  1. ...  3.  1.  1.]
 ...
 [ 5. 10. 10. ...  8. 10.  2.]
 [ 4.  8.  6. ... 10.  6.  1.]
 [ 4.  8.  8. ... 10.  4.  1.]]
0


C:\Users\felip\AppData\Local\Temp\ipykernel_22668\1543715793.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X.fillna(method = 'ffill',inplace=True)
C:\Users\felip\AppData\Local\Temp\ipykernel_22668\1543715793.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna(method = 'ffill',inplace=True)


# mfeat


In [25]:
data_mfeat = pd.read_csv('data/UCI/multiple+features/mfeat-kar', sep='\s+',
                         header=None,
                         names=['x'+str(i) for i in range(1,65)])
data_mfeat['class'] = 0
for i, row in data_mfeat.iterrows():
    data_mfeat.loc[i,'class'] = i//200

X = data_mfeat.drop(['class'], axis=1)
y = data_mfeat[['class']]
X = X.to_numpy()
dataset_utils.fvecs_write("fvec_datasets/mfeat.fvec", X)

# Mnist

In [31]:
(train_X, train_y), (test_X, test_y) = mnist.load_data()

train_X = train_X.reshape(-1,28*28)
dataset_utils.fvecs_write("fvec_datasets/mnist.fvec",train_X)